<?php 

return [
    ['title' => 'Nederland', 'value' => 'NL'],
    ['title' => 'België', 'value' => 'BE'],
    ['title' => 'Duitsland', 'value' => 'DE'],
    ['title' => 'Bulgarije', 'value' => 'BG'],
    ['title' => 'Cyprus', 'value' => 'CY'],
    ['title' => 'Denemarken', 'value' => 'DK'],
    ['title' => 'Estland', 'value' => 'EE'],
    ['title' => 'Finland', 'value' => 'FI'],
    ['title' => 'Frankrijk', 'value' => 'FR'],
    ['title' => 'Griekenland', 'value' => 'GR'],
    ['title' => 'Hongarije', 'value' => 'HU'],
    ['title' => 'Ierland', 'value' => 'IE'],
    ['title' => 'Italië', 'value' => 'IT'],
    ['title' => 'Kroatië', 'value' => 'HR'],
    ['title' => 'Letland', 'value' => 'LV'],
    ['title' => 'Litouwen', 'value' => 'LT'],
    ['title' => 'Luxemburg', 'value' => 'LU'],
    ['title' => 'Malta', 'value' => 'MT'],
    ['title' => 'Oostenrijk', 'value' => 'AT'],
    ['title' => 'Polen', 'value' => 'PL'],
    ['title' => 'Portugal', 'value' => 'PT'],
    ['title' => 'Roemenië', 'value' => 'RO'],
    ['title' => 'Slovenië', 'value' => 'SI'],
    ['title' => 'Slowakije', 'value' => 'SK'],
    ['title' => 'Spanje', 'value' => 'ES'],
    ['title' => 'Tsjechië', 'value' => 'CZ'],
    ['title' => 'Zweden', 'value' => 'SE'],
];